package se.yrgo.dataaccess;

import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;
import se.yrgo.services.customers.CustomerNotFoundException;

@Repository
public class CustomerDaoJdbcTemplateImpl  implements CustomerDao{
    private static final String CREATE_CUSTOMER = "CREATE TABLE CUSTOMER (CUSTOMER_ID VARCHAR(50), " +
            "COMPANY_NAME VARCHAR(255), EMAIL VARCHAR(50), TELEPHONE VARCHAR(20), NOTES VARCHAR(255))";
    private static final String CREATE_CONTACT = "CREATE TABLE CONTACT (CONTACT_ID integer generated by default as identity (start with 1), " +
            "CUSTOMER_ID VARCHAR(50), CONTACT_DATE DATE, NOTES VARCHAR(255))";
    private static final String DELETE_CUSTOMER = "DELETE FROM CUSTOMER WHERE CUSTOMER_ID=?";
    private static final String DELETE_CONTACT = "DELETE FROM CONTACT WHERE CONTACT_ID=?";
    private static final String PURGE_CONTACTS = "DELETE FROM CONTACT WHERE CUSTOMER_ID=?";
    private static final String UPDATE_CUSTOMER = "UPDATE CUSTOMER SET COMPANY_NAME=?, EMAIL=?, TELEPHONE=?, NOTES=? WHERE CUSTOMER_ID=?";
    private static final String INSERT_CUSTOMER = "INSERT INTO CUSTOMER (CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES) VALUES (?,?,?,?,?)";
    private static final String INSERT_CONTACT = "INSERT INTO CONTACT (CUSTOMER_ID, CONTACT_DATE, NOTES) VALUES (?,?,?)";
    private static final String GET_CUSTOMER = "SELECT CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES FROM CUSTOMER WHERE CUSTOMER_ID=?";
    private static final String GET_CONTACT = "SELECT CONTACT_DATE, NOTES FROM CONTACT WHERE CUSTOMER_ID=?";

    private JdbcTemplate template;

    @Autowired
    public CustomerDaoJdbcTemplateImpl(JdbcTemplate template){
        this.template = template;
    }

    public void create(Customer customer){
        template.update(INSERT_CUSTOMER, customer.getCustomerId(),customer.getCompanyName(), customer.getEmail(), customer.getTelephone(), customer.getNotes());
    }

    @PostConstruct
    public void createTables(){
        try{
            template.update(CREATE_CUSTOMER);
            template.update(CREATE_CONTACT);
            }
        catch (Exception e){
            System.out.println("Tables already exist");
        }
    }

    public Customer getById(String customerId) throws RecordNotFoundException{
            return template.queryForObject(GET_CUSTOMER, new CustomerRowMapper(), customerId);
    }

    public List<Customer> getByName(String customer){
        return template.query("SELECT CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES FROM CUSTOMER WHERE COMPANY_NAME=?",
                new CustomerRowMapper(), customer);
    }

    public void update(Customer customerToUpdate) throws RecordNotFoundException{
        template.update(UPDATE_CUSTOMER, customerToUpdate.getCompanyName(), customerToUpdate.getEmail(),
                customerToUpdate.getTelephone(), customerToUpdate.getNotes(), customerToUpdate.getCustomerId());
    }

    public void delete(Customer oldCustomer) throws RecordNotFoundException{
        template.update(DELETE_CUSTOMER, oldCustomer.getCustomerId());
    }

    public List<Customer> getAllCustomers(){
        return template.query("SELECT * FROM CUSTOMER", new CustomerRowMapper());
    }

    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException{
            Customer customer = template.queryForObject(GET_CUSTOMER, new CustomerRowMapper(), customerId);
            List<Call> calls = template.query(GET_CONTACT, new ContactRowMapper(), customerId);
            customer.setCalls(calls);
            return customer;
    }

    public void addCall(Call newCall, String customerId){
        template.update(INSERT_CONTACT, customerId, newCall.getTimeAndDate(), newCall.getNotes());
    }

    public void deleteCall(int contactId){
        template.update(DELETE_CONTACT, contactId);
    }

    public void purgeCalls(String customerId){
        template.update(PURGE_CONTACTS, customerId);
    }

    class CustomerRowMapper implements RowMapper<Customer> {
        public Customer mapRow(ResultSet rs, int arg1) throws SQLException 	{
            String customerId = rs.getString(1);
            String companyName = rs.getString(2);
            String email = rs.getString(3);
            String telephone = rs.getString(4);
            String notes = rs.getString(5);

            return new Customer("" + customerId, companyName, email, telephone, notes);
        }
    }

    class ContactRowMapper implements RowMapper<Call> {
        public Call mapRow(ResultSet rs, int arg1) throws SQLException 	{
            Date date = rs.getDate("CONTACT_DATE");
            String notes = rs.getString("NOTES");

            return new Call(notes, date);
        }
    }

}
